# Generated by Django 6.0.7 on 2026-08-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliercontact',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='suppliernote',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='suppliernote',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='supplierproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='supplier',
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='suppliers_s_phone_af9b45_idx',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('MANUFACTURER', 'Manufacturer'), ('WHOLESALER', 'Wholesaler'), ('DISTRIBUTOR', 'Distributor'), ('IMPORTER', 'Importer')], default='WHOLESALER', max_length=20),
        ),
        migrations.DeleteModel(
            name='SupplierContact',
        ),
        migrations.DeleteModel(
            name='SupplierNote',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='average_quality_score',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='bank_routing_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='outstanding_amount',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='products',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tax_exempt',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='trading_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='SupplierProduct',
        ),
    ]
