[project]
name = "inventory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "celery>=5.6.3",
    "celery-starter>=1.0.9",
    "django>=6.0.7",
    "django-celery>=3.1.17",
    "django-celery-beat>=2.9.0",
    "django-celery-results",
    "django-celeryx==0.1.0a2",
    "django-cors-headers==4.7.0",
    "django-environ==0.12.0",
    "django-filter>=26.1",
    "django-jazzmin>=3.0.5",
    "django-redis==6.0",
    "django-silk>=5.5.0",
    "djangorestframework==3.16.0",
    "eventlet>=0.41.1",
    "flower==2.0.1",
    "gunicorn>=26.0.0",
    "pillow>=12.3.0",
    "pip>=26.2.1",
    "psycopg2-binary>=2.9.12",
    "python-decouple>=3.8",
    "redis==7.0",
    "rest-framework-simplejwt>=0.0.2",
    "sslcommerz-lib==1.0",
    "whitenoise>=6.12.0",
]
