# Generated by Django 6.0.7 on 2026-08-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customergroup',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='customernote',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customernote',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_c_custome_47da94_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('RETAIL', 'Retail Customer'), ('WHOLESALE', 'Wholesale Customer'), ('CORPORATE', 'Corporate Customer'), ('VIP', 'VIP Customer')], default='RETAIL', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20),
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
        migrations.DeleteModel(
            name='CustomerGroup',
        ),
        migrations.DeleteModel(
            name='CustomerNote',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_email_subscribed',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_sms_subscribed',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='price_level',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tax_exempt',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='website',
        ),
    ]
