# Generated by Django 6.0.7 on 2026-08-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_Tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_model',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
