# Generated by Django 6.0.7 on 2026-08-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productattribute_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Product dimensions (L x W x H)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of additional product images'),
        ),
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text="Key features/highlights of the product. e.g., ['Feature 1', 'Feature 2']"),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description for product listing', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text="Product specifications in JSON format. e.g., {'Brand': 'Apple', 'Model': 'iPhone 15', 'Color': 'Black'}"),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Product video URL (YouTube/Vimeo)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_period',
            field=models.IntegerField(default=0, help_text='Warranty period in months'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in kg', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Full product description with details'),
        ),
    ]
